/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Getting started',
      items: [
        'getting-started',
        'authentication',
        'errors',
        'pagination-filtering',
      ],
    },
    {
      type: 'category',
      label: 'Business flows',
      items: [
        'flows/api-request-lifecycle',
        'flows/authentication-and-access',
        'flows/candidate-lifecycle',
        'flows/staff-review-and-support',
        'flows/permanent-intake',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'operations/scheduled-processes',
        'operations/external-integrations',
        'operations/webhooks',
        'operations/queue-and-events',
      ],
    },
    {
      type: 'category',
      label: 'API reference',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
  ],
};

export default sidebars;
